legacybook_server/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from account.views import profile, register, CustomLogoutView

urlpatterns = [
    path('register', register, name='register_user'),
    path('login', auth_views.LoginView.as_view(
        template_name='account/login.html'
    ), name='login_view'),
    path('logout', CustomLogoutView.as_view(
        template_name='account/logged_out.html'
    ), name='logout_view'),

    path('profile', profile, name='account_profile')
]

legacybook_server/core/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import logger_health_check
from marketing.views import homepage

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", homepage, name="homepage"),
    path("account/", include("account.urls")),
    path("logger-health-check", logger_health_check),
    path("graveyard/", include("graveyard.urls", namespace="graveyard")),
    path("marketing/", include("marketing.urls", namespace="marketing"))
]

legacybook_server/graveyard/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from graveyard.views import person_erasing, register_decedent


app_name = 'graveyard'
urlpatterns = [
    path('register-decedent', register_decedent, name='register_decedent'),
    path('person-erasing', person_erasing, name='person_erasing'),
]

legacybook_server/marketing/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path


app_name = 'marketing'
urlpatterns = [
]

legacybook_server/account/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from account import manager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=255, blank=True)
    middle_name = models.CharField(_('middle name'), max_length=255, blank=True)
    last_name = models.CharField(_('last name'), max_length=255, blank=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('is staff'), default=False)

    USERNAME_FIELD = 'email'

    objects = manager.UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

legacybook_server/graveyard/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class Decedent(models.Model):
    first_name = models.CharField(_('first name'), max_length=255)
    middle_name = models.CharField(_('middle name'), max_length=255, blank=True, null=True)
    last_name = models.CharField(_('last name'), max_length=255)
    date_of_birth = models.DateField(_('date of birth'), blank=True, null=True)
    date_of_death = models.DateField(_('date of death'))

legacybook_server/marketing/models.py
from django.db import models

# Create your models here.

legacybook_server/account/forms.py
from django import forms
from django.contrib.auth import get_user_model


class RegisterUserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def save(self, commit=True):
        user = super(RegisterUserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

legacybook_server/graveyard/forms.py
from functools import partial

from django import forms

from graveyard.models import Decedent


CustomDateInput = partial(forms.DateInput, {'class': 'datepicker'})

class DecedentForm(forms.ModelForm):

    class Meta:
        model = Decedent
        fields = '__all__'
        widgets = {
            'date_of_birth': CustomDateInput(),
            'date_of_death': CustomDateInput(),
        }

legacybook_server/account/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.shortcuts import redirect, render

from account.forms import RegisterUserForm


class CustomLogoutView(LogoutView):

    def get_next_page(self):
        next_page = super(CustomLogoutView, self).get_next_page()
        messages.add_message(
            self.request, messages.SUCCESS,
            'Vous avez été déconnecté avec success!'
        )
        return next_page


def register(request):

    if request.user.is_authenticated:
        return redirect('account_profile')

    register_form = RegisterUserForm()
    if request.method == 'POST':
        register_form = RegisterUserForm(request.POST)
        if register_form.is_valid():
            register_form.save()
            email = register_form.cleaned_data['email']
            password = register_form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                messages.add_message(
                    request, messages.SUCCESS,
                    'Votre compte a été créé avec success!'
                )
                return redirect('account_profile')
            else:
                # Should never happen, as we just created this user
                # and we used the exact same email/password to create it
                # TODO: raise a proper log when configured.
                pass

    return render(request, 'account/register.html', {
        'register_form': register_form
    })


@login_required
def profile(request):
    return render(request, 'account/profile.html')

legacybook_server/core/views.py
def logger_health_check(request):
    raise Exception("Raising Exception to check if the logger is working.")

legacybook_server/graveyard/views.py
from django.shortcuts import render
from django.contrib import messages

from graveyard.forms import DecedentForm

# Create your views here.
def register_decedent(request):
    decedent_form = DecedentForm()
    if request.method == 'POST':
        decedent_form = DecedentForm(request.POST)
        if decedent_form.is_valid():
            decedent_form.save()
            return render(request, 'graveyard/register_decedent_successful.html')

    return render(request, 'graveyard/register_decedent.html', {
        'decedent_form': decedent_form
    })


def person_erasing(request):
    return render(request, 'graveyard/person_erasing.html')

legacybook_server/marketing/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def homepage(request):
    return render(request, 'marketing/index.html')

legacybook_server/graveyard/templates/graveyard/person_erasing.html
{% extends 'account/account_base.html' %}

{% block page-content %}

<section id="person-erasing" class="text-white">
    <h1>Nettoyer.</h1>

    <p>On définit des champs de base et un pack pour un prix et on laisse un champ libre pour les demandes particuliaires.</p>
    <p>Possibilité de tout remplir et d'enregistrer car il est temps de passer à la caisse...</p>
</section>
{% endblock page-content %}

legacybook_server/graveyard/templates/graveyard/register_decedent.html
{% extends 'account/account_base.html' %}

{% load bootstrap4 %}

{% bootstrap_css %}

{% block extra-css %}
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
{% endblock extra-css %}

{% block extra-js %}
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script>
    $(function () {
        const today = new Date();
        const currentYear = today.getFullYear();

        $(".datepicker").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "1700:" + currentYear,
            maxDate: today
        });
    });
</script>
{% endblock extra-js %}

{% block page-content %}

<section id="register-decedent" class="text-white">
    <h1>Enregistrer un défunt.</h1>
    
    <p>Pour pouvoir enregistrer un nouveau défunt, nous avons besoin de quelques informations :</p>
    <form action="{% url 'graveyard:register_decedent' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form decedent_form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    {% endbuttons %}
    </form>
</section>
{% endblock page-content %}

legacybook_server/graveyard/templates/graveyard/register_decedent_successful.html
{% extends 'account/account_base.html' %}

{% block page-content %}
<section id="register-decedent-successful" class="text-white">
    <p>Vous avez enregistré un nouveau défunt avec succès.</p>
</section>
{% endblock page-content %}